# Generated by Django 5.1.5 on 2025-02-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_WEATHER'),
    ]

    operations = [
    ]
