# Generated by Django 5.1.5 on 2025-02-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_WEATHER'),
    ]

    operations = [
    ]
