# Generated by Django 5.1.5 on 2025-02-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_WEATHER'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(db_column='city', max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(db_column='temperature'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weather_description',
            field=models.CharField(db_column='weather_description', max_length=255),
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='WEATHER',
        ),
    ]
