# Generated by Django 5.1.5 on 2025-02-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_weatherdata_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='id2',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='city_id',
            field=models.IntegerField(db_column='city_id', default=0),
        ),
    ]
